language: php

php:
  - 7.3
  - 8.0

cache:
  directories:
    - $HOME/.composer/cache/files
    - $HOME/.cache/composer/files

before_script:
  - phpenv config-rm xdebug.ini
  - composer self-update
  - COMPOSER_MEMORY_LIMIT=-1 composer install --prefer-source --no-interaction --no-suggest --no-progress

script:
  - vendor/bin/phpcs
  - vendor/bin/phpunit

branches:
  only:
    - master